---
title: 'R Notebook: o-well 3'
author: "Rachel Judd [rachel.judd]"
output:
  html_document:
    df_print: paged
---
# Setting up Remote Access
```{r}
which.github = "remote";  # local ... remote 

github.local = "C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/";
github.remote = "https://raw.githubusercontent.com/RachelJudd/WSU_STATS419_Spring2021/main/";



if(which.github == "remote")
  {
  mypath = paste0(github.remote, "workspace/o-well/")
  # include.me = paste0(github.remote,"https://raw.githubusercontent.com/RachelJudd/WSU_STATS419_Spring2021/main/functions/functions-intro.R");
#   library(devtools);
#   source_url(include.me);
  } else {
    mypath = paste0(github.local, "workspace/o-well/")
#           include.me = paste0( github.local, "functions/functions-intro.R");
#           library(devtools);
#           source(include.me);
  }
path.data = paste0(mypath, "data/")
```


```{r}
storeToPipe = function(df, file, header=TRUE, quote="", sep="|", row.names=FALSE)
  {
  if(quote == "") { quote = FALSE; }
  utils::write.table(df, file=file, quote=quote, col.names=header, row.names=row.names, sep=sep);
  }

readFromPipe = function(file, header=TRUE, quote="", sep="|")
  {
  utils::read.csv(file, header=header, quote=quote, sep=sep);
  }
```

# Reading in the Data
```{r}
file = paste0(path.data, "saudi2.txt");
# readFromPipe(file, header=TRUE, quote="", sep="|");
saudi2 = data.frame(readFromPipe(file, header=TRUE, quote="", sep="|"))
```


# Descriptive Statistics
```{r}
#https://stackoverflow.com/questions/23163863/mean-of-a-column-in-a-data-frame-given-the-columns-name
summary(saudi2[["As"]]);
sd(saudi2[["As"]]);
boxplot(saudi2[["As"]]);
```

```{r}
summary(saudi2[["B"]]);
sd(saudi2[["B"]]);
boxplot(saudi2[["B"]]);
```

```{r}
summary(saudi2[["Ba"]]);
sd(saudi2[["Ba"]]);
boxplot(saudi2[["Ba"]]);
```

```{r}
summary(saudi2[["Be"]]);
sd(saudi2[["Be"]]);
boxplot(saudi2[["Be"]]);
```

```{r}
summary(saudi2[["Cd"]]);
sd(saudi2[["Cd"]]);
boxplot(saudi2[["Cd"]]);
```

```{r}
summary(saudi2[["Co"]]);
sd(saudi2[["Co"]]);
boxplot(saudi2[["Co"]]);
```

```{r}
summary(saudi2[["Cr"]]);
sd(saudi2[["Cr"]]);
boxplot(saudi2[["Cr"]]);
```

```{r}
summary(saudi2[["Cu"]]);
sd(saudi2[["Cu"]]);
boxplot(saudi2[["Cu"]]);
```

```{r}
summary(saudi2[["Fe"]]);
sd(saudi2[["Fe"]]);
boxplot(saudi2[["Fe"]]);
```

```{r}
summary(saudi2[["Hg"]]);
sd(saudi2[["Hg"]]);
boxplot(saudi2[["Hg"]]);
```

```{r}
summary(saudi2[["Mn"]]);
sd(saudi2[["Mn"]]);
boxplot(saudi2[["Mn"]]);
```

```{r}
summary(saudi2[["Mo"]]);
sd(saudi2[["Mo"]]);
boxplot(saudi2[["Mo"]]);
```

```{r}
summary(saudi2[["Pb"]]);
sd(saudi2[["Pb"]]);
boxplot(saudi2[["Pb"]]);
```

```{r}
summary(saudi2[["Se"]]);
sd(saudi2[["Se"]]);
boxplot(saudi2[["Se"]]);
```

```{r}
summary(saudi2[["Zn"]]);
sd(saudi2[["Zn"]]);
boxplot(saudi2[["Zn"]]);
```

```{r}
summary(saudi2[["pH"]]);
sd(saudi2[["pH"]]);
boxplot(saudi2[["pH"]]);
```

```{r}
summary(saudi2[["Eh"]]);
sd(saudi2[["Eh"]]);
boxplot(saudi2[["Eh"]]);
```

```{r}
summary(saudi2[["TDS"]]);
sd(saudi2[["TDS"]]);
boxplot(saudi2[["TDS"]]);
```

```{r}
summary(saudi2[["Ca"]]);
sd(saudi2[["Ca"]]);
boxplot(saudi2[["Ca"]]);
```

```{r}
summary(saudi2[["K"]]);
sd(saudi2[["K"]]);
boxplot(saudi2[["K"]]);
```

```{r}
summary(saudi2[["Mg"]]);
sd(saudi2[["Mg"]]);
boxplot(saudi2[["Mg"]]);
```

```{r}
summary(saudi2[["Na"]]);
sd(saudi2[["Na"]]);
boxplot(saudi2[["Na"]]);
```

```{r}
summary(saudi2[["HCO3"]]);
sd(saudi2[["HCO3"]]);
boxplot(saudi2[["HCO3"]]);
```

```{r}
summary(saudi2[["Cl"]]);
sd(saudi2[["Cl"]]);
boxplot(saudi2[["Cl"]]);
```

```{r}
summary(saudi2[["SO4"]]);
sd(saudi2[["SO4"]]);
boxplot(saudi2[["SO4"]]);
```

```{r}
summary(saudi2[["NO3"]]);
sd(saudi2[["NO3"]]);
boxplot(saudi2[["NO3"]]);
```

```{r}
summary(saudi2[["F"]]);
sd(saudi2[["F"]]);
boxplot(saudi2[["F"]]);
```

```{r}
summary(saudi2[["PO4"]]);
sd(saudi2[["PO4"]]);
boxplot(saudi2[["PO4"]]);
```

```{r}
summary(saudi2[["TH"]]);
sd(saudi2[["TH"]]);
boxplot(saudi2[["TH"]]);
```

```{r}
summary(saudi2[["TA"]]);
sd(saudi2[["TA"]]);
boxplot(saudi2[["TA"]]);
```

```{r}
summary(saudi2[["TS"]]);
sd(saudi2[["TS"]]);
boxplot(saudi2[["TS"]]);
```

```{r}
summary(saudi2[["SS"]]);
sd(saudi2[["SS"]]);
boxplot(saudi2[["SS"]]);
```

```{r}
summary(saudi2[["COD"]]);
sd(saudi2[["COD"]]);
boxplot(saudi2[["COD"]]);
```

```{r}
summary(saudi2[["BOD"]]);
sd(saudi2[["BOD"]]);
boxplot(saudi2[["BOD"]]);
```

```{r}
summary(saudi2[["DO"]]);
sd(saudi2[["DO"]]);
boxplot(saudi2[["DO"]]);
```

```{r}
summary(saudi2[["Latitude"]]);
sd(saudi2[["Latitude"]]);
boxplot(saudi2[["Latitude"]]);
```

```{r}
summary(saudi2[["Longitude"]]);
sd(saudi2[["Longitude"]]);
boxplot(saudi2[["Longitude"]]);
```

```{r}
summary(saudi2[["Altitude"]]);
sd(saudi2[["Altitude"]]);
boxplot(saudi2[["Altitude"]]);
```

```{r}
summary(saudi2[["Fault"]]);
sd(saudi2[["Fault"]]);
boxplot(saudi2[["Fault"]]);
```

```{r}
# print(saudi2[["Geology"]]);
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

v = c("sand,granite","sand,granite,alkaline","alkaline,conglomerate","alkaline","volcanic,granite","volcanic","gypsum","alkaline","gypsum","volcanic,conglomerate","alkaline,granite","granite,alkaline","gypsum","gypsum","volcanic","volcanic,granite,alkaline","gypsum,conglomerate","sand","sand","sand","sand","sand","alkaline,granite");
getmode(v);
```

# Correlations between Altitude and Water Quality Measures
```{r}
cor(saudi2[["Altitude"]],saudi2[["pH"]]);

```

```{r}
cor(saudi2[["Altitude"]],saudi2[["As"]])
```

```{r}
cor(saudi2[["Altitude"]], saudi2[["B"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Ba"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Be"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Cd"]])

```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Co"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Cr"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Cu"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Fe"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Hg"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Mn"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Mo"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Pb"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Se"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Zn"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Eh"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["TDS"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Ca"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["K"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Mg"]])
```
```{r}
cor(saudi2[["Altitude"]],saudi2[["Na"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["HCO3"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Cl"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["SO4"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["NO3"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["F"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["PO4"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["TH"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["TA"]])
```
```{r}
cor(saudi2[["Altitude"]],saudi2[["TS"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["SS"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["COD"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["BOD"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["DO"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Latitude"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Longitude"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Fault"]])
```

```{r}
cor(saudi2[["Altitude"]],saudi2[["Distance.to.Water"]])
```


# Correlations between pH and Latitude, Longitude, and Distance to Fault
```{r}
cor(saudi2[["Fault"]],saudi2[["pH"]])
```

```{r}
cor(saudi2[["Latitude"]],saudi2[["pH"]])
```

```{r}
cor(saudi2[["Longitude"]],saudi2[["pH"]])
```

