---
title: "data-intro"
author: Rachel Judd [rachel.judd]
output: html_notebook
---
# Setup
```{r}
library(devtools);
# install_github("MonteShaffer/imdb/imdb");
library(imdb);
?loadDataIMDB
```

```{r}
# install.packages("D:/R-Data/humanVerseWSU/humanVerseWSU_0.1.4.zip", repos = NULL, type = "source");
# library(humanVerseWSU);
# install.packages("D:/R-Data/IMDB/imdb_0.1.1.zip", repos=NULL, type="source");
# library(imdb)
```

```{r}
loadDataIMDB();  # will populate a global list of data:  imdb.data
```


# Will Smith
```{r}
IMDB.searchPersonName("Will* Smith", 1:3);
```

```{r}
will = list();
will$nmid = "nm0000226"
```

```{r}
will$movies = IMDB.getMoviesForPerson(will$nmid);
will$ttids = will$movies$ttid

```

```{r}
loadInflationData()
```

```{r}
will$movies = standardizeDollarsInDataFrame(will$movies, 2000, "millions", "year","millions2000")
will$movies = replaceFactorColumnWithIndicatorVariables(will$movies, "genre", use.boolean = FALSE)
```

```{r}
summary(will$movies[["rank"]]);
boxplot(will$movies[["rank"]]);
```

```{r}
summary(will$movies[["year"]]);
boxplot(will$movies[["year"]]);
```

```{r}

summary(will$movies[["minutes"]]);
boxplot(will$movies[["minutes"]]);
```

```{r}
summary(will$movies[["ratings"]]);
boxplot(will$movies[["ratings"]]);
```

```{r}
summary(will$movies[["metacritic"]]);
boxplot(will$movies[["metacritic"]]);
```

```{r}
summary(will$movies[["votes"]]);
boxplot(will$movies[["votes"]]);
```

```{r}
summary(will$movies[["millions"]]);
boxplot(will$movies[["millions"]]);
```

```{r}
summary(will$movies[["millions2000"]]);
boxplot(will$movies[["millions2000"]]);

# summary(will$movies[["rank"]])
# boxplot(will$movies)
```
The filter functions used below came from these links:
<https://github.com/peytonurquhart/WSU_STAT_419/blob/main/functions/functions-imdb.R>
<https://github.com/peytonurquhart/WSU_STAT_419/blob/main/imdb/data-intro.Rmd>
```{r}
# na.omit(will$movies)
filterBy = function(df, col, lambda)
{
  first = TRUE;
  ndf = NULL;
  
  for(i in 1:nrow(df))
  {
    if(lambda(df[i,col]) == TRUE)
    {
      if (first)
      {
        ndf <- df[c(i),];
        first = FALSE;
      } else {
        ndf <- rbind(ndf, df[c(i), ]);
      }
    }
  }
  return(ndf);
}

filterOutMissingValues = function(df, col)
{
  return(filterBy(df, col, (function(x) {!(is.na(x))})))
}

getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
   
};
```

```{r}

will.minusNA = filterOutMissingValues(will$movies, 26);
v = will.minusNA[["rated"]]
getmode(v);
# print(getmode(v));
```
```{r}
will.minusNA = filterOutMissingValues(will$movies, 4);
v = will.minusNA[["year"]]
getmode(v);
```
```{r}
will.minusNA = filterOutMissingValues(will$movies, 6);
v = will.minusNA[["genre"]]
getmode(v);
```
```{r}
will.minusNA = filterOutMissingValues(will$movies, 27);
v = will.minusNA[["ratings"]]
getmode(v);
```
```{r}
will.minusNA = filterOutMissingValues(will$movies, 28);
v = will.minusNA[["metacritic"]]
getmode(v);
```


# Denzel Washington
```{r}
IMDB.searchPersonName("Denzel Washington", 1:3);
```

```{r}

denzel = list();
denzel$nmid = "nm0000243"

denzel$movies = IMDB.getMoviesForPerson(denzel$nmid);
denzel$ttids = denzel$movies$ttid
denzel$movies =  standardizeDollarsInDataFrame(denzel$movies, 2000, "millions", "year","millions2000")
denzel$movies = replaceFactorColumnWithIndicatorVariables(denzel$movies, "genre", use.boolean = FALSE)
```

```{r}
summary(denzel$movies[["rank"]]);
boxplot(denzel$movies[["rank"]]);
```

```{r}
summary(denzel$movies[["year"]]);
boxplot(denzel$movies[["year"]]);
```

```{r}

summary(denzel$movies[["minutes"]]);
boxplot(denzel$movies[["minutes"]]);
```

```{r}
summary(denzel$movies[["ratings"]]);
boxplot(denzel$movies[["ratings"]]);
```

```{r}
summary(denzel$movies[["metacritic"]]);
boxplot(denzel$movies[["metacritic"]]);
```

```{r}
summary(denzel$movies[["votes"]]);
boxplot(denzel$movies[["votes"]]);
```

```{r}
summary(denzel$movies[["millions"]]);
boxplot(denzel$movies[["millions"]]);
```

```{r}
summary(denzel$movies[["millions2000"]]);
boxplot(denzel$movies[["millions2000"]]);
```

```{r}

denzel.minusNA = filterOutMissingValues(denzel$movies, 24);
v = denzel.minusNA[["rated"]]
getmode(v);
# print(getmode(v));
```

```{r}
denzel.minusNA = filterOutMissingValues(denzel$movies, 4);
v = denzel.minusNA[["year"]]
getmode(v);
```

```{r}
denzel.minusNA = filterOutMissingValues(denzel$movies, 6);
v = denzel.minusNA[["genre"]]
getmode(v);
```

```{r}
denzel.minusNA = filterOutMissingValues(denzel$movies, 25);
v = denzel.minusNA[["ratings"]]
getmode(v);
```

```{r}
denzel.minusNA = filterOutMissingValues(denzel$movies, 26);
v = denzel.minusNA[["metacritic"]]
getmode(v);
```

# Did Will Smith and Denzel Washington work together?
```{r}
intersect(denzel$ttids, will$ttids)
```
<https://www.imdb.com/title/tt1546668/>
```{r}
info = subset(imdb.data$movies.df$info,ttid == "tt1546668")
```
Since the movie that they have in common is a documentary, it is likely that Will Smith and Denzel Washington did not actually work together. 

```{r}
# loadInflationData()
```

# Comparison in same dataframe
```{r}
DW = merge(will$movies, denzel$movies, all = TRUE)
```

```{r}
max(DW$millions2000, na.rm = TRUE) #belongs to Will smith
```
```{r}
min(DW$millions2000, na.rm = TRUE) #also Will smith
```
```{r}
# colSums(DW$movies$millions2000, dim = 1)

boxplot(will$movies$millions2000,denzel$movies$millions2000, names = c("Will Smith","Denzel Washington"), ylab = "Standardized Millions");
dif=(336.026-120.0872)/336.026
```
```{r}
meanEarningDifference = (81.87-48.76)/81.87
```

```{r}
max(DW$ratings, na.rm = TRUE);
boxplot(will$movies$ratings,denzel$movies$ratings, names = c("Will","Denzel"), ylab = "Ratings") #Will has lowest rating (2.3 in 2006), also the highest at 8.6 in 2003
```

```{r}
boxplot(will$movies$metacritic,denzel$movies$metacritic, names = c("Will","Denzel"), ylab = "Metacritic")
```
```{r}
max(DW$votes, na.rm = TRUE);
boxplot(will$movies$votes,denzel$movies$votes, names = c("Will Smith","Denzel Washington"), ylab = "Votes") #will got highest and lowest votes. Lowest year was 2005, highest 2007.
```

```{r}
boxplot(will$movies$year,denzel$movies$year, names = c("Will","Denzel"), ylab = "Year") #will got his money in a shorter amount of time
```
```{r}
#  x = will$movies$genre.action
# colSums(x)
```

# Read in Excel Files
```{r}
library(readxl);
denzel_Washington_Data <- read_excel("C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/workspace/will-v-denzel/denzel-is-better/denzel_Washington_Data.xlsx",col_types = c("text", "text", "text", 
        "numeric", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "text", "numeric"));
denzel_Washington_Data <- subset (denzel_Washington_Data, select = -1)
rownames(denzel_Washington_Data) = c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","TOTALS","PROPORTION");


```

```{r}
# denzelRatingFrequency = as.data.frame(table(denzel_Washington_Data[["rating"]]))
# denzelRatingFrequency$Proportion = c(0.016393443,0.016393443,0.06557377,0.032786885,0.032786885,0.016393443,0.032786885,0.032786885,0.081967213,0.098360656,0.016393443,0.049180328,0.032786885,0.016393443,0.049180328,0.098360656,0.016393443,0.016393443,0.032786885,0.06557377,0.049180328,0.016393443)
```

```{r}
library(readxl);
denzelRatingFrequency = read_excel("C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/workspace/will-v-denzel/denzel-is-better/denzelFrequency&Proportion.xlsx")
#Proportion(61) is proportion of all movies
#Proportion(55) is proportion of all rated movies
```


```{r}
hist(denzelRatingFrequency[["ratings"]], main = paste("Histogram of Denzel Washington Ratings"), xlab = "Ratings", xlim = range(0,10));
```

```{r}
denzelNotTotal = read_excel("C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/workspace/will-v-denzel/denzel-is-better/denzel_Washington_Data.xlsx",col_types = c("text", "text", "text", 
        "numeric", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "text", "numeric"), n_max = 61);
denzel_Washington_Data <- subset (denzel_Washington_Data, select = -1)
```

```{r}
hist(denzelNotTotal[["votes"]], main = paste("Histogram of Denzel Washington Votes"), xlab = "Votes", xlim = range(1800,390000));
```


```{r}
denzel_Data_Abbreviated = denzel_Washington_Data[1:61,8:21]
prop=denzel_Data_Abbreviated #proportion
prop[,1]=prop[,1]/sum(prop[,1]);
prop[,2]=prop[,2]/sum(prop[,2]);
prop[,3]=prop[,3]/sum(prop[,3]);
prop[,4]=prop[,4]/sum(prop[,4]);
prop[,5]=prop[,5]/sum(prop[,5]);
prop[,6]=prop[,6]/sum(prop[,6]);
prop[,7]=prop[,7]/sum(prop[,7]);
prop[,8]=prop[,8]/sum(prop[,8]);
prop[,9]=prop[,9]/sum(prop[,9]);
prop[,10]=prop[,10]/sum(prop[,10]);
prop[,11]=prop[,11]/sum(prop[,11]);
prop[,12]=prop[,12]/sum(prop[,12]);
prop[,13]=prop[,13]/sum(prop[,13]);
prop[,14]=prop[,14]/sum(prop[,14]);
proportion = rbind(denzel_Data_Abbreviated, prop);
colSums(prop);
```
```{r}
plot(denzelNotTotal[["year"]], denzelNotTotal[["rating"]], ylim = range(0,10), ylab = "Rating", xlab = "Year", pch = 19, col = "black", main = paste("Consistency of Ratings Across Denzel Washington's Career"))
```
```{r}
plot(denzelNotTotal[["year"]], denzelNotTotal[["rating"]], ylim = range(0,10), ylab = "Rating", xlab = "Year", pch = 19, col = "black", xlim = range(1980,2021), main = paste("Consistency of Ratings Across Denzel Washington's Career"))
par(new=TRUE)
plot(WillNotTotal[["year"]], WillNotTotal[["rating"]], ylim = range(0,10), ylab = "Rating", xlab = "Year", pch = 19, col = "red", xlim = range(1980,2021), main = paste("Consistency of Ratings Across Denzel Washington's Career"))
```

```{r}
plot(denzelNotTotal[["year"]], denzelNotTotal[["millions2000"]], ylab = "Millions 2000", ylim = range(0,180), xlim = range(1980,2021),xlab = "Year", pch = 19, col = "black", main = paste("Consistency of Earnings Across Denzel Washington's Career"))
par(new=TRUE)
plot(WillNotTotal[["year"]], WillNotTotal[["millions2000"]], ylim = range(0,180),  pch = 19,  xlim = range(1980,2021), ylab = "", xlab = "",  col = "red")
```



```{r}
plot(denzelNotTotal[["year"]], denzelNotTotal[["millions2000"]], ylab = "Millions2000", xlab = "Year", pch = 19, col = "black", main = paste("Consistency of Earnings Across Denzel Washington's Career"))
```



```{r}
library(readxl);
Will_Smith_Data <- read_excel("C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/workspace/will-v-denzel/denzel-is-better/WillSmithData.xlsx", col_types = c("text", "text", "text", 
        "numeric", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", 
        "numeric"), n_max = 113);
Will_Smith_Data <- subset (Will_Smith_Data, select = -1)
rownames(Will_Smith_Data) = c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","TOTALS","PROPORTION");


View(Will_Smith_Data)
```

```{r}
# willRatingFrequency = as.data.frame(table(Will_Smith_Data[["rating"]]))
willMinutesFrequency = as.data.frame(table(Will_Smith_Data[["minutes"]]))
```


```{r}
library(readxl);
willRatingFrequency <- read_excel("C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/workspace/will-v-denzel/denzel-is-better/WillFrequency.xlsx")
```


```{r}
hist(willRatingFrequency[["ratings"]], main = paste("Histogram of Will Smith Ratings"), xlab = "Ratings", xlim = range(0,10), ylim = range(0,12))
```
```{r}
# x = denzel_Washington_Data[["rating"]]
# y=Will_Smith_Data[["rating"]]
# hist(x,y, main = paste("Histogram of Denzel Washington Ratings"), xlab = "Ratings", xlim = range(0,10))
```

```{r}
WillNotTotal <- read_excel("C:/_git_/github/RachelJudd/WSU_STATS419_Spring2021/workspace/will-v-denzel/denzel-is-better/WillSmithData.xlsx", col_types = c("text", "text", "text", 
        "numeric", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric"), n_max = 111);
WillNotTotal <- subset (WillNotTotal, select = -1)
```
```{r}
hist(WillNotTotal[["votes"]], main = paste("Histogram of Will Smith Votes"), xlab = "Votes");
```

```{r}
plot(denzelNotTotal[["year"]], denzelNotTotal[["votes"]], ylim = range(0,600000), ylab = "Votes", xlab = "Year", pch = 19, col = "black", xlim = range(1980,2021), main = paste("Consistency of Votes Across Career"))
par(new=TRUE)
plot(WillNotTotal[["year"]], WillNotTotal[["votes"]], ylim = range(0,600000),ylab = "Votes", xlab = "Year", pch = 19, col = "red", xlim = range(1980,2021))
```
```{r}
plot(denzelNotTotal[["year"]], denzelNotTotal[["metacritic"]], ylim = range(0,100), ylab = "Metacritic", xlab = "Year", pch = 19, col = "black", xlim = range(1980,2021), main = paste("Consistency of Metacritic Across Denzel Washington's Career"))
par(new=TRUE)
plot(WillNotTotal[["year"]], WillNotTotal[["metacritic"]], ylim = range(0,100), ylab = "", xlab = "Year", pch = 19, col = "red", xlim = range(1980,2021))
```

```{r}
boxplot(will$movies$metacritic,denzel$movies$metacritic, names = c("Will Smith","Denzel Washington"), ylab = "Metacritic")
```

